---
title: "Notes"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Getting started
Clone SRA2R Project from GitHub
```{r eval=FALSE}
file > New Project... > Version Control > Git > Repository URL: https://github.com/rosachoe/SRA2R.git
```

Set Project to SRA2R
```{r eval=FALSE}
install.packages("roxygen2")
### SRAdb
source("https://bioconductor.org/biocLite.R")
biocLite("SRAdb")

library(roxygen2)
library(devtools)
library(SRAdb)
load_all()
```

## Download/Load SQLite database
```{r eval=FALSE} 
if(file.exists('SRAmetadb.sqlite')) {
  sra_dbname = 'SRAmetadb.sqlite'
  sra_con = dbConnect(dbDriver("SQLite"), sra_dbname)
} else {
  getSRAdbFile(destdir = getwd(), destfile = "SRAmetadb.sqlite.qz", method)
}
```

## Isolating controlled access reads
In Terminal:
```{r eval=FALSE}
wget ftp://ftp-trace.ncbi.nlm.nih.gov/sra//reports/Metadata/SRA_Accessions.tab
```

In R:
```{r eval=FALSE}
cmd_cut = "cut -f 1,9 $PWD/SRA_Accessions.tab"
df = read.delim(pipe(cmd_cut))
private_df = df[df$Visibility == 'controlled_access',]
```

### Usage
Getting public access reads from search
```{r eval=FALSE} 
accs = getSRA(search_terms = "breast cancer homo sapiens", sra_con = sra_con, acc_only = TRUE)
accs = accs[!(accs$run %in% private_df$Accession),"run"]
```

Getting aligned reads
```{R eval=FALSE}
accs = getReferenceCount(accs)
```

GenomicAlignments, GenomicReads, ShortRead
```{R eval=FALSE}
source("https://bioconductor.org/biocLite.R")
biocLite("ShortRead")
biocLite("GenomicReads")
biocLite("GenomicAlignments")
```

GenomicAlignments vs GenomicReads
```{R eval=FALSE}
GenomicReads takes in manual input of lists for ranges and represents these locations as a table, whereas GenomicAlignments takes in files (.BAM) and converts them to a table form similar to that of GenomicReads. They can be used in conjunction, where GenomicReads would represent a constant set of locations, such as where a specific gene is located, and GenomicAlignments would represent reads from a specific organism/sample. Using the %over% function allows us to see if the samples overlap with the gene of interest.
```

Shared Files with Local Machine and Docker
```{R eval=FALSE}
1. Download file to Local Machine
2. docker-machine scp (-rcp) <filename> default:<filename>
3. docker run -v /home/docker/<filename>:<filename>
```